core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issue_tracker.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.deletion import get_candidate_relations_to_delete

from issue_tracker.validators import MinLengthValidator


class CustomModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=50, null=False, blank=False, unique=True)

    def __str__(self):
        return '{}'.format(self.status)


class Type(models.Model):
    type = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.type)


class Task(models.Model):
    summary = models.CharField(
        max_length=50, null=False, blank=False,
        validators=(MinLengthValidator(5),)
    )
    description = models.TextField(max_length=1000, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_deleted = models.BooleanField(default=False)
    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save(update_fields=['is_deleted', ])

    type = models.ManyToManyField(
        'issue_tracker.Type',
        related_name='tasks',
        blank=False
    )

    project = models.ForeignKey(
        'issue_tracker.Project',
        related_name='tasks',
        on_delete=models.CASCADE,
        verbose_name='Проект',
        default=1
    )

    def __str__(self):
        return '{}. {}'.format(self.pk, self.summary)


class Project(models.Model):
    project = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=False)
    updated_at = models.DateTimeField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)
    objects = CustomModelManager()
    user = models.ManyToManyField(
        get_user_model(), related_name='projects',
        verbose_name='Пользователь'
    )

    def delete(self, using=None, keep_parents=False):  # noqa C901
        self.is_deleted = True
        delete_candidates = get_candidate_relations_to_delete(self.__class__._meta)
        if delete_candidates:
            for rel in delete_candidates:
                if rel.on_delete.__name__ == 'CASCADE' and rel.one_to_many and not rel.hidden:
                    for item in getattr(self, rel.related_name).all():
                        item.delete()
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f'{self.project}'

templates/common/delete_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Вы действительно хотите удалить задачу:</p>
                <p style="color: red">{{ deleted_object.summary }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="POST" action="{% url 'delete_task' deleted_object.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/common/delete_modal_project.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Вы действительно хотите удалить проект:</p>
                <p style="color: red">{{ deleted_object.project }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <form method="POST" action="{% url 'delete_project' deleted_object.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/common/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'list_project' %}">Список проектов</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/tasks/' %} active {% endif %}" aria-current="page"
                       href="{% url 'list_task' %}">Список задач</a>
                </li>
                {% if perms.issue_tracker.change_project %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/projects/add/' %} active {% endif %}"
                           aria-current="page"
                           href="{% url 'create_project' %}">Добавить проект</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'profile' request.user.pk %}">Привет, {{ user.first_name|capfirst }}</a>
                    </li>
                    {% if perms.auth.view_user %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/accounts/profiles/' %} active {% endif %}" aria-current="page"
                               href="{% url 'profile_users' %}">Пользователи</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/accounts/logout/' %} active {% endif %}"
                           aria-current="page"
                           href="{% url 'logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/accounts/login/' %} active {% endif %}"
                           aria-current="page"
                           href="{% url 'login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/accounts/register/' %} active {% endif %}"
                           aria-current="page"
                           href="{% url 'register' %}">Зарегистрироваться</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <form class="d-flex" method="get">
            <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="search"
                   value="{{ form.search.value|default:'' }}">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
            {% for error in form.search.errors %}
                <p class="form-error" style="color: red">{{ error }}</p>
            {% endfor %}
        </form>
    </div>
</nav>

templates/common/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1{% if query %}&{{ query }}{% endif %}">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}{% if query %}&{{ query }}{% endif %}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if query %}&{{ query }}{% endif %}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}{% if query %}&{{ query }}{% endif %}">В конец &raquo;</a>
    </span>
</div>