core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issue_tracker.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.deletion import get_candidate_relations_to_delete

from issue_tracker.validators import MinLengthValidator


class CustomModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=50, null=False, blank=False, unique=True)

    def __str__(self):
        return '{}'.format(self.status)


class Type(models.Model):
    type = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.type)


class Task(models.Model):
    summary = models.CharField(
        max_length=50, null=False, blank=False,
        validators=(MinLengthValidator(5),)
    )
    description = models.TextField(max_length=1000, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_deleted = models.BooleanField(default=False)
    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save(update_fields=['is_deleted', ])

    type = models.ManyToManyField(
        'issue_tracker.Type',
        related_name='tasks',
        blank=False
    )

    project = models.ForeignKey(
        'issue_tracker.Project',
        related_name='tasks',
        on_delete=models.CASCADE,
        verbose_name='Проект',
        default=1
    )

    def __str__(self):
        return '{}. {}'.format(self.pk, self.summary)


class Project(models.Model):
    project = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=False)
    updated_at = models.DateTimeField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)
    objects = CustomModelManager()
    user = models.ManyToManyField(
        get_user_model(), related_name='projects',
        verbose_name='Пользователь'
    )

    def delete(self, using=None, keep_parents=False):  # noqa C901
        self.is_deleted = True
        delete_candidates = get_candidate_relations_to_delete(self.__class__._meta)
        if delete_candidates:
            for rel in delete_candidates:
                if rel.on_delete.__name__ == 'CASCADE' and rel.one_to_many and not rel.hidden:
                    for item in getattr(self, rel.related_name).all():
                        item.delete()
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f'{self.project}'

issue_tracker/views/project_view.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from issue_tracker.models import Project
from issue_tracker.helpers import SearchView
from issue_tracker.forms import SearchForm, ProjectForm
from django.contrib.auth.mixins import PermissionRequiredMixin


class ListProjectView(PermissionRequiredMixin, SearchView):
    template_name = 'project/list_project.html'
    model = Project
    ordering = ('-created_at',)
    paginate_by = 5
    paginate_orphans = 1
    context_object_name = 'projects'
    search_form = SearchForm
    search_fields = {
        'project': 'icontains'
    }
    extra_context = {
        'title': 'Сприсок проектов'
    }
    permission_required = 'issue_tracker.view_project'

    def has_permission(self):
        for project in Project.objects.all():
            if super().has_permission() and self.request.user in project.user.all():
                return True


class CreateProjectView(PermissionRequiredMixin, CreateView):
    model = Project
    template_name = 'project/create_project.html'
    form_class = ProjectForm
    permission_required = 'issue_tracker.add_project'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = request.user
            project = Project.objects.create(
                project=form.cleaned_data.get('project'),
                description=form.cleaned_data.get('description'),
                created_at=form.cleaned_data.get('created_at'),
                updated_at=form.cleaned_data.get('updated_at')
            )
            project.user.add(user)
            url = reverse('detail_project', kwargs={'pk': project.pk})
            return HttpResponseRedirect(url)
        return render(request, self.template_name, context={
            'form': form
        })


class DeleteProjectView(PermissionRequiredMixin, DeleteView):
    model = Project
    permission_required = 'issue_tracker.delete_project'

    def get(self, request, *args, **kwargs):
        return self.delete(request=request)

    def get_success_url(self):
        return reverse('list_project')

    def has_permission(self):
        if self.request.user.is_staff \
                or self.request.user.groups.all()[0].name == 'Project Manager':
            return True
        elif super().has_permission() and self.request.user in self.get_object().user.all():
            return True
        return False


class DetailProjectView(DetailView):
    context_object_name = 'project'
    model = Project
    template_name = 'project/detail_project.html'


class UpdateProjectView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/update_project.html'
    model = Project
    form_class = ProjectForm
    permission_required = 'issue_tracker.change_project'

    def get_success_url(self):
        return reverse('detail_project', kwargs={'pk': self.get_object().pk})

    def has_permission(self):
        if super().has_permission() or self.request.user.is_staff or \
                self.request.user.groups.all()[0].name == 'Project Manager':
            return True
        return False


class AddUsersToProject(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/add_users_to_project.html'
    fields = ['user']
    permission_required = 'auth.change_user'

    def get_success_url(self):
        return reverse('detail_project', kwargs={'pk': self.get_object().pk})

    def has_permission(self):
        return super().has_permission() and self.request.user \
            in self.get_object().user.all() or self.request.user.is_staff

templates/project/add_users_to_project.html
{% extends 'base.html' %}

{% block content %}

    <h4>Добавить пользователя</h4>
    <form method="POST" action="{% url 'add_users_to_project' project.pk %}" style="margin-top: 20px; width: 70%;">
        {% csrf_token %}
        {% for user in form.user.field.queryset %}
            {% if user == request.user %}
                <div class="form-check form-switch">
                    <label class="form-check-label">{{ user.get_full_name }}</label>
                    <input class="form-check-input" id="user"
                           name="user" type="checkbox" {% if user in project.user.all %} checked hidden {% endif %}
                           value="{{ user.pk }}">
                </div>
            {% else %}
                <div class="form-check form-switch">
                    <label class="form-check-label">{{ user.get_full_name }}</label>
                    <input class="form-check-input" id="user"
                           name="user" type="checkbox" {% if user in project.user.all %} checked {% endif %}
                           value="{{ user.pk }}">
                </div>
            {% endif %}
        {% endfor %}
        <input type="submit" class="form-control btn btn-secondary" value="Добавить">
    </form>
{% endblock %}

templates/project/create_project.html
{% extends 'base.html' %}

{% block content %}

    <h4>Создать проект</h4>
    <form method="POST" action="{% url 'create_project' %}" style="margin-top: 20px; width: 70%;">
        {% csrf_token %}
        {% include 'partial/project/form_project.html' with button_text='Создать' %}
    </form>
{% endblock %}

templates/project/detail_project.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <p>Участники проекта: </p>
            {% for user in project.user.all %}
                <div style="display: inline-flex;">
                    <h6 class="card"><a class="nav-link " aria-current="page"
                                        href="{% url 'profile' user.pk %}">{{ user.get_full_name }}</a>
                    </h6>
                </div>
            {% endfor %}
            <div class="card-title">Наименование проекта: {{ project.project }}</div>
            {% if project.description %}
                <p>Описание проекта: {{ project.description }}</p>
            {% else %}
                <p>Описание проекта не задано</p>
            {% endif %}
            {% if project.created_at %}
                <p>Дата начало: {{ project.created_at|date:'d.m.Y G:i' }}</p>
            {% else %}
                <p>Дата начало не задано</p>
            {% endif %}
            {% if project.updated_at %}
                <p>Дата окончания: {{ project.updated_at|date:'d.m.Y G:i' }}</p>
            {% else %}
                <p>Дата окончания не задано</p>
            {% endif %}

            <a class="btn btn-dark" href="{% url 'list_project' %}">Вернуться в список проектов</a>

            {% if perms.issue_tracker.change_project %}
                <a class="btn btn-success" href="{% url 'update_project' project.pk %}">Изменить</a>
            {% endif %}
            {% if perms.issue_tracker.delete_project or user.is_staff %}
                <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">Удалить
                </button>
            {% endif %}
            {% if perms.auth.change_user and user in project.user.all or user.is_staff %}
                <a class="btn btn-success" href="{% url 'add_users_to_project' project.pk %}">Управление
                    пользователями</a>
            {% endif %}
            {% if perms.issue_tracker.add_task and user in project.user.all or user.is_staff %}
                <h4 style="margin-top: 20px;">Создание задачи для данного проекта</h4>
                <form action="{% url 'new_task' project.pk %}" method="post">
                    {% include 'partial/task/form_task.html' with button_text='Создать' %}
                </form>
            {% else %}
                <h5 style="margin-top: 20px;"> Авторизуйтесь, чтобы добавить задачу для проекта либо у вас нету
                    доступа</h5>
            {% endif %}

        </div>
    </div>
    {% include 'common/delete_modal_project.html' with deleted_object=project %}
    {% if project.tasks %}
        {% include 'partial/task/list_task_project.html' with tasks=project.tasks.all %}
    {% endif %}
{% endblock %}

templates/project/list_project.html
{% extends 'base.html' %}

{% block content %}

    {% include 'partial/project/profiles_project_list.html' %}


    {% if is_paginated %}
        {% include 'common/pagination.html' %}
    {% elif not projects %}
        <div class="col py-4" style="text-align: center; color: red">
            <h4>Ошибка 404: по данному поиску: "{{ form.search.value }}"</h4>
            <h4>задачи не найдены</h4>
        </div>
    {% endif %}
{% endblock %}

templates/project/update_project.html
{% extends 'base.html' %}

{% block content %}
    <h4>Изменить проект</h4>
    <form method="POST" action="{% url 'update_project' project.pk %}" style="margin-top: 20px; width: 70%;">
        {% csrf_token %}
        {% include 'partial/project/form_project.html' with button_text='Изменить' %}
    </form>
{% endblock %}